# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 1
  - name: News
    url: news/
    weight: 2
  - name: Publication
    url: publication/
    weight: 3
  - name: Team
    url: team/
    weight: 4
  - name: Teaching
    url: teaching/
    weight: 5
  - name: Contact
    url: contact
    weight: 6
